import { API_TYPE } from "utils/helper";

// AUTH
export const LOGIN = API_TYPE("LOGIN");
export const SIGNUP = API_TYPE("SIGNUP");
export const LOGOUT_USER = "LOGOUT_USER";

// PAYROLL_RUN
export const GET_PAYROLL_RUN = API_TYPE("GET_PAYROLL_RUN");
export const SET_SELECTED_PAYROLLRUN = "SET_SELECTED_PAYROLLRUN";
export const CREATE_BULK_TRANSACTION = API_TYPE("CREATE_BULK_TRANSACTION");
export const GET_TRANSACTIONS = API_TYPE("GET_TRANSACTIONS");
export const SET_SELECTED_TRANSACTION = "SET_SELECTED_TRANSACTION";

// PAYROLL
export const GET_PAYROLL = API_TYPE("GET_PAYROLL");
export const ADD_PAYROLL = API_TYPE("ADD_PAYROLL");
export const ADD_EDIT_PAYROLL = API_TYPE("ADD_EDIT_PAYROLL");
export const UPDATE_PAYROLL = API_TYPE("UPDATE_PAYROLL");
export const DELETE_PAYROLL = API_TYPE("DELETE_PAYROLL");

// PROFILE
export const GET_PROFILE = API_TYPE("GET_PROFILE");
export const UPDATE_PROFILE = API_TYPE("UPDATE_PROFILE");

// PAYMENT
export const UPDATE_PAYMENT = API_TYPE("UPDATE_PAYMENT");

// REIMBURSEMENT
export const GET_REIMBURSEMENT = API_TYPE("GET_REIMBURSEMENT");
export const ADD_REIMBURSEMENT = API_TYPE("ADD_REIMBURSEMENT");
export const UPDATE_REIMBURSEMENT = API_TYPE("UPDATE_REIMBURSEMENT");
export const DELETE_REIMBURSEMENT = API_TYPE("DELETE_REIMBURSEMENT");
export const ADD_EDIT_REIMBURSEMENT = API_TYPE("ADD_EDIT_REIMBURSEMENT");
export const UPDATE_REIMBURSEMENT_STATUS = API_TYPE(
  "UPDATE_REIMBURSEMENT_STATUS"
);
export const GET_REIMBURSEMENT_LIMITS = API_TYPE("GET_REIMBURSEMENT_LIMITS");
export const SET_SELECTED_REIMBURSEMENTS = "SET_SELECTED_REIMBURSEMENTS";

// Dashboard
export const FETCH_ADMIN_DASHBOARD = API_TYPE("FETCH_ADMIN_DASHBOARD");
export const FETCH_EMPLOYEE_DASHBOARD = API_TYPE("FETCH_EMPLOYEE_DASHBOARD");

// EMPLOYEE
export const GET_EMPLOYEE = API_TYPE("GET_EMPLOYEE");
export const ADD_EMPLOYEE = API_TYPE("ADD_EMPLOYEE");
export const UPDATE_EMPLOYEE = API_TYPE("UPDATE_EMPLOYEE");
export const DELETE_EMPLOYEE = API_TYPE("DELETE_EMPLOYEE");
export const ADD_EDIT_EMPLOYEE = API_TYPE("ADD_EDIT_EMPLOYEE");
export const UPDATE_EMPLOYEE_STATUS = API_TYPE("UPDATE_EMPLOYEE_STATUS");
export const SET_SELECTED_EMPLOYEES = "SET_SELECTED_EMPLOYEES";

// FINANCIAL
export const GET_FINANCIAL = API_TYPE("GET_FINANCIAL");
export const ADD_FINANCIAL = API_TYPE("ADD_FINANCIAL");
export const UPDATE_FINANCIAL = API_TYPE("UPDATE_FINANCIAL");
export const DELETE_FINANCIAL = API_TYPE("DELETE_FINANCIAL");
export const ADD_EDIT_FINANCIAL = API_TYPE("ADD_EDIT_FINANCIAL");
export const GET_FINANCIAL_HISTORY = API_TYPE("GET_FINANCIAL_HISTORY");
export const UPDATE_FINANCIAL_STATUS = API_TYPE("UPDATE_FINANCIAL_STATUS");

export const SET_SELECTED_FINANCIALS = "SET_SELECTED_FINANCIALS";

// EXPENSES
export const GET_EXPENSE = API_TYPE("GET_EXPENSE");
export const ADD_EXPENSE = API_TYPE("ADD_EXPENSE");
export const UPDATE_EXPENSE = API_TYPE("UPDATE_EXPENSE");
export const DELETE_EXPENSE = API_TYPE("DELETE_EXPENSES");
export const ADD_EDIT_EXPENSE = API_TYPE("ADD_EDIT_EXPENSE");
export const UPDATE_EXPENSE_STATUS = API_TYPE("UPDATE_EXPENSE_STATUS");

export const SET_SELECTED_EXPENSES = "SET_SELECTED_EXPENSES";

// PERKS
export const GET_PERKS = API_TYPE("GET_PERKS");

// COMMON
export const GET_EXCHANGE_RATE = API_TYPE("GET_EXCHANGE_RATE");
export const GET_CURRENCIES = API_TYPE("GET_CURRENCIES");
export const SHOW_DETAILS = "SHOW_DETAILS";
// LAYOUT
export const CHANGE_LAYOUT = "CHANGE_LAYOUT";
export const CHANGE_LAYOUT_WIDTH = "CHANGE_LAYOUT_WIDTH";
export const CHANGE_SIDEBAR_THEME = "CHANGE_SIDEBAR_THEME";
export const CHANGE_SIDEBAR_THEME_IMAGE = "CHANGE_SIDEBAR_THEME_IMAGE";
export const CHANGE_SIDEBAR_TYPE = "CHANGE_SIDEBAR_TYPE";

// topbar
export const CHANGE_TOPBAR_THEME = "CHANGE_TOPBAR_THEME";
// show sidebar
export const SHOW_SIDEBAR = "SHOW_SIDEBAR";
export const TOGGLE_LEFTMENU = "TOGGLE_LEFTMENU";
/* RIGHT SIDEBAR */
export const SHOW_RIGHT_SIDEBAR = "SHOW_RIGHT_SIDEBAR";
// Preloader
export const CHANGE_PRELOADER = "CHANGE_PRELOADER";

// ROLES
export const GET_ROLES = API_TYPE("GET_ROLES");
export const ADD_ROLES = API_TYPE("ADD_ROLES");
export const UPDATE_ROLES = API_TYPE("UPDATE_ROLES");
export const DELETE_ROLES = API_TYPE("DELETE_ROLES");
export const ADD_EDIT_ROLES = API_TYPE("ADD_EDIT_ROLES");
export const GET_ROLES_LISTING = API_TYPE("GET_ROLES_LISTING");
